### ISSUE TITLE
Link to examples is corrupt

### ISSUE THREAD

**Issue by salotz** [statgen/qplot#1]
The link to the examples of qplots tried to open some page that started talking to me about having a virus and crap, it also tried to mount some external hard drive. I would suggest removing it immediately.

**Comment by hyunminkang** [comment]
Thanks for letting us know. It was supposed to link our wiki http://genome.sph.umich.edu/ but the site was redirected to mywiki.com, which contains virus and crap. I don't know why, but I guess it was human mistake when we created this site because I don't see any evidence that the file was maliciously changed.

**Comment by hyunminkang** [comment]
BTW, the issue should now be fixed. Let me know otherwise.
